# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "tasks"

development:
  <<: *common
  brokers:
    - localhost:9092

test:
  <<: *common
  brokers:
    - localhost:9092
