defaults: &defaults
  pool: 10
  connection_timeout: 2

development: &development
  <<: *defaults
  hosts:
    - "localhost:22181"
  pool: 10
  chroot: '/uberpopug_development'

test:
  <<: *defaults
  <<: *development
  chroot: '/uberpopug_test'
